import {test,expect} from '@playwright/test';
test('standalone flow: local assets, J2, countries, analysis, exports, stale results and restored custom observer',async({page})=>{
  const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if((/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:8080'))||r.url().includes('/api/'))external.push(r.url());});
  await page.goto('/');await expect(page.locator('#status')).toContainText('준비 완료');
  await expect(page.locator('#workspace-title')).toHaveText('통신·항법 통합 궤도 배치');await expect(page.locator('#snapshot-metrics')).toContainText('최선 링크 처리량');expect(await page.locator('#nav-performance').evaluate(el=>el.open)).toBe(true);await expect(page.locator('#globe')).toHaveAttribute('data-navigation','visible');await page.locator('#nav-performance > summary').click();await expect(page.locator('#globe')).toHaveAttribute('data-navigation','visible');await page.locator('#nav-performance > summary').click();await page.locator('[data-tab="analysis"]').click();await expect(page.locator('#sidebar-title')).toHaveText('분석 조건');
  expect(await page.locator('#nav-settings').evaluate(el=>el.open)).toBe(true);await expect(page.locator('[data-config="leoNav"]')).toBeVisible();await expect(page.locator('[data-config="leoNav"]')).toBeChecked();
  await expect(page.locator('[data-country]:checked')).toHaveCount(1);await expect(page.locator('[data-country="KOR"]')).toBeChecked();await page.locator('[data-tab="design"]').click();await expect(page.locator('[data-config="j2"]')).toBeChecked();await page.locator('[data-tab="analysis"]').click();
  await page.locator('#duration').fill('20');await page.locator('#step').fill('60');await page.locator('#run').click();await expect(page.locator('#status')).toHaveText('분석 완료');
  await expect(page.locator('#station-table tbody tr')).toHaveCount(3);await expect(page.locator('#period-metrics')).toContainText('통신 목표 충족률');await expect(page.locator('#period-metrics')).toContainText('처리량 중앙값');expect(await page.locator('#analysis-nav-performance').evaluate(el=>el.open)).toBe(true);await expect(page.locator('#nav-period-metrics')).toContainText('항법 목표 충족률');await expect(page.locator('#nav-comparison tbody tr')).toHaveCount(3);
  const downloaded=page.waitForEvent('download');await page.locator('#export-json').click();const download=await downloaded;const stream=await download.createReadStream();const chunks=[];for await(const c of stream)chunks.push(c);const data=JSON.parse(Buffer.concat(chunks).toString());expect(data.observers[0].samples).toHaveLength(21);expect(data.metadata.input_sha256).toHaveLength(64);
  await page.locator('[data-tab="design"]').click();await page.locator('[data-config="altitude"]').fill('888');await page.locator('[data-config="altitude"]').blur();await page.locator('[data-tab="analysis"]').click();await expect(page.locator('#analysis-note')).toContainText('이전 설정');
  await page.locator('#add-observer').click();await page.locator('.custom-observer [data-key="name"]').fill('Custom test');await page.locator('.custom-observer [data-key="lat"]').fill('-25.5');await page.locator('.custom-observer [data-key="lon"]').fill('179.9');await page.locator('.custom-observer [data-key="lon"]').blur();
  const saved=page.waitForEvent('download');await page.locator('#save-scenario').click();const savedFile=await saved;const savedStream=await savedFile.createReadStream();const savedChunks=[];for await(const c of savedStream)savedChunks.push(c);const json=Buffer.concat(savedChunks);
  await page.locator('#scenario-file').setInputFiles({name:'scenario.json',mimeType:'application/json',buffer:json});await expect(page.locator('.custom-observer [data-key="lat"]')).toHaveValue('-25.5');
  await page.locator('[data-tab="design"]').click();await page.locator('#earth-style').selectOption('outline');await expect(page.locator('#globe')).toHaveAttribute('data-earth-style','outline');await page.locator('#earth-style').selectOption('image');await expect(page.locator('#globe')).toHaveAttribute('data-earth-style','image');await page.locator('#earth-style').selectOption('outline');await page.locator('#map-mode').selectOption('2d');await page.locator('#map-mode').selectOption('2d-globe');await page.locator('#map-mode').selectOption('2d-map');await page.locator('#map-mode').selectOption('3d');await page.locator('#show-heatmap').check();await page.locator('#show-footprint').check();await page.locator('#route').click();await expect(page.locator('#route-result')).toContainText('ms');
  await page.evaluate(()=>{scrollTo(0,0);document.querySelector('.sidebar').scrollTop=0;});await page.screenshot({path:'outputs/standalone-desktop.png',fullPage:true});
  expect(errors).toEqual([]);expect(external).toEqual([]);
});
test('multi-shell, TLE and cancellation stay usable',async({page})=>{
  await page.goto('/');await expect(page.locator('#status')).toContainText('준비 완료');await page.locator('[data-config="mode"]').selectOption('multi_shell');await page.locator('#add-shell').click();await expect(page.locator('#orbit-note')).toContainText('2개 층');
  await page.locator('[data-config="mode"]').selectOption('tle');await page.locator('#example-tle').click();await expect(page.locator('#orbit-note')).toContainText('SGP4');await expect(page.locator('#error')).toBeHidden();await page.locator('[data-tab="analysis"]').click();
  await page.locator('#duration').fill('10');await page.locator('#step').fill('60');await page.locator('#run').click();await expect(page.locator('#status')).toHaveText('분석 완료');
  await page.locator('[data-tab="design"]').click();await page.locator('[data-config="mode"]').selectOption('walker');await page.locator('[data-tab="analysis"]').click();await page.locator('#duration').fill('1440');await page.locator('#step').fill('60');await page.locator('#run').click();await page.locator('#cancel').click();await expect(page.locator('#status')).toHaveText('계산을 취소했습니다.');await expect(page.locator('#run')).toBeEnabled();
  await page.locator('#duration').fill('10');await page.locator('[data-tab="trade"]').click();await page.locator('#run-trade').click();await expect(page.locator('#status')).toHaveText('분석 완료');await expect(page.locator('#trade-table tbody tr')).toHaveCount(6);
  await page.locator('#sweep-axis').selectOption('altitude');await page.locator('#sweep').click();await expect(page.locator('#sweep-note')).toContainText('순간 성능');await expect(page.locator('#sweep-rate svg')).toHaveCount(1);
});
test('mobile layout runs with locally served assets',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.locator('#status')).toContainText('준비 완료');await page.locator('#toggle-settings').click();await page.locator('[data-tab="analysis"]').click();await page.locator('#duration').fill('5');await page.locator('#run').click();await expect(page.locator('#status')).toHaveText('분석 완료');
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);expect(overflow).toBe(false);await page.screenshot({path:'outputs/standalone-mobile.png',fullPage:true});
});
